### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by GizmoHotaru** [softwaremagico/ThinkMachine-Advisor#1]
Hi, im no programmer, at all... just the FadingSuns fan.... till now im using my not-so perfect LibreCalc sheet to generate NPC, and this i found. So again, hot to use it, im interested in the desctop version of this app.

**Comment by softwaremagico** [comment]
Hi Gizmo.

The application has been just started and is far from finished. I am just developing the first steps of the application, but is not possible to be executed now. Please, be patient due to it will take time.

**Comment by softwaremagico** [comment]
The first release version is now available on the Google Play platform, and is accessible to anybody. If you wish you can now search for it and install it by free.
