### ISSUE TITLE
Google Play App

### ISSUE THREAD

**Issue by System0verl0ad** [softwaremagico/ThinkMachine-Advisor#2]
Hey,
Thank you for putting this together. As someone not super familiar with use of github, was looking for character generator for Fading Suns, found your project.
Sadly, did not see the Google play app as instructed in readme.
Happy to try and figure out how to make it work on desktop but could use some direction.

Should I just download Maven, try a pull request and follow the run instructions found on https://github.com/softwaremagico/ThinkMachine  ?

Appreciate any guidance!

**Comment by softwaremagico** [comment]
I am sorry, but the app is still in beta and only the beta testers can
download it.
It is taking long to finish it, but I will release sooner or later.

Regards

**Comment by softwaremagico** [comment]
The first release version is now available on the Google Play platform, and is accessible to anybody. If you wish you can now search for it and install it by free.
